import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeChanger } from "@/components/nav/theme-changer";
import { ThemeProvider } from "next-themes";
import { Navbar } from "@/components/nav/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          <div className="container min-h-screen m-auto flex justify-center items-center">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
