import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Navbar } from "@/components/nav/navbar";
import AOSComponent from "@/components/util/aos";
import { getUser } from "@/actions/acara";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AOSComponent>
            <Navbar />
            <div className="flex justify-center container max-md:p-8">
              {children}
            </div>
          </AOSComponent>
        </ThemeProvider>
      </body>
    </html>
  );
}
